TestStore.Web/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using TestStore.Application.Dto;
using TestStore.Application.Usecases.Commands;
using TestStore.Implementation.Exceptions;
using TestStore.Implementation.Usecases;
using TestStore.Web.Core;

namespace TestStore.Web.Controllers
{
    public class AuthController : Controller
    {
        private UsecaseHandler _handler;
        public AuthController(UsecaseHandler handler)
        {
            _handler = handler;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login([FromForm] UserLoginDto dto, [FromServices] JWTManager manager, [FromServices] IHttpContextAccessor ctx)
        {
            //return RedirectToAction("Index", dto);
            var tokens = manager.MakeTokens(dto.Username, dto.Password);
            ctx.HttpContext.Response.Headers["set-cookie"]  = "access=" + tokens[0];
            return Ok(new { access = tokens[0], refresh = tokens[1] });
        }

        [HttpPost]
        public IActionResult Create([FromForm] CreateUserDto dto, [FromServices] ICreateUserCommand command)
        {
                this._handler.HandleCommand(command, dto);
                return StatusCode(201);
        }
        [HttpGet]
        public IActionResult Register()
        {
            return this.View();
        }
    }
}

TestStore.Web/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TestStore.Application.Dto;
using TestStore.Application.Usecases.Commands;
using TestStore.Implementation.Usecases;
using TestStore.Web.Core;

namespace TestStore.Web.Controllers
{

    public class CartController : Controller
    {
        private UsecaseHandler _handler;
        private AuthService _service;
        public CartController(UsecaseHandler handler, AuthService service)
        {
            _handler = handler;
            this._service = service;
        }
        public IActionResult Index()
        {
            if (this._service.Authenticated)
            {
                return View();
            }
            return RedirectToAction("Index", "Auth");
        }

        [HttpDelete]
        public IActionResult Delete(int id, [FromServices] IDeleteCartCommand command)
        {
            if (this._service.Authenticated)
            {
                this._handler.HandleCommand(command, id);
                return NoContent();
            }
            return RedirectToAction("Index", "Auth");
        }

        [HttpPost]
        public IActionResult Store([FromForm] CartDto dto, [FromServices] ICreateCartCommand command)
        {
            if (this._service.Authenticated)
            {
                this._handler.HandleCommand(command, dto);
                return StatusCode(201);
            }
            return RedirectToAction("Index", "Auth");
        }
    }
}

TestStore.Web/ViewComponents/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TestStore.Application.Dto;
using TestStore.Implementation.DataAccess;

namespace TestStore.Web.ViewComponents
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private static  readonly TestStoreDbContext _context = new TestStoreDbContext(); 

        //public static   Microsoft.AspNetCore.Mvc.ViewComponents.ViewViewComponentResult GetNavLinks()
        //{
        //    var navLinks = _context.NavLinks.Select(x => new NavLinkDto
        //    {
        //        Name = x.Name,
        //        Action = x.Action,
        //        Controller = x.Controller
        //    }).ToList();
        //    return View(navLinks);
        //}
    }
}

TestStore.Web/Views/Shared/_Layout.cshtml
@using TestStore.Web.ViewComponents
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestStore.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestStore.Web.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.27.2/axios.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @await Component.InvokeAsync("NavigationMenu")
@*                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestStore.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Registration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Index">Sign in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index" id="accessCart">Cart</a>
                        </li>
                    </ul>
                </div>
*@            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TestStore.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="module">
        import token from "/js/jwtmanager.js";
        $("#accessCart").click(function(e){
            e.preventDefault();
            if(token.content()){
                location.href="/Cart";
            }else {
                alert("You have to be authorized in order to access cart");
            }
        });

        $("#logout").click(function(e){
            e.preventDefault();
            document.cookie = "access=; MaxAge=-99999999";
            location.href="/";
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>