TestStore.Web/Controllers/AdminpanelController.cs
using Microsoft.AspNetCore.Mvc;
using TestStore.Web.Core;

namespace TestStore.Web.Controllers
{
    public class AdminpanelController : Controller
    {
        private AuthService _service;
        public AdminpanelController(AuthService service)
        {
            _service = service;
        }
        public IActionResult Index()
        {
            if (this._service.Authenticated)
            {
                return View();
            }
            return RedirectToAction("Index", "Auth");
        }
    }
}

TestStore.Web/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using TestStore.Application.Dto;
using TestStore.Application.Usecases.Commands;
using TestStore.Implementation.Exceptions;
using TestStore.Implementation.Usecases;
using TestStore.Web.Core;

namespace TestStore.Web.Controllers
{
    public class AuthController : Controller
    {
        private UsecaseHandler _handler;
        public AuthController(UsecaseHandler handler)
        {
            _handler = handler;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login([FromForm] UserLoginDto dto, [FromServices] JWTManager manager, [FromServices] IHttpContextAccessor ctx)
        {
            //return RedirectToAction("Index", dto);
            var tokens = manager.MakeTokens(dto.Username, dto.Password);
            ctx.HttpContext.Response.Headers["set-cookie"]  = "access=" + tokens[0];
            return Ok(new { access = tokens[0], refresh = tokens[1] });
        }

        [HttpPost]
        public IActionResult Create([FromForm] CreateUserDto dto, [FromServices] ICreateUserCommand command)
        {
                this._handler.HandleCommand(command, dto);
                return StatusCode(201);
        }
        [HttpGet]
        public IActionResult Register()
        {
            return this.View();
        }
    }
}

TestStore.Web/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using TestStore.Application.Dto;
using TestStore.Application.Usecases.Commands;
using TestStore.Application.Usecases.Queries;
using TestStore.Implementation.Usecases;
using TestStore.Web.Core;

namespace TestStore.Web.Controllers
{
    public class UsersController : Controller
    {
        private UsecaseHandler _handler;
        private AuthService _service;

        public UsersController(UsecaseHandler handler, AuthService service)
        {
            _handler = handler;
            _service = service;
        }

        [HttpGet]
       public IActionResult Edit(int id, [FromServices] IGetUserQuery query)
        {
            if (this._service.Authenticated)
            {
                var user = this._handler.HandleQuery(query, id);
                    
                return View(user);
            }
            return RedirectToAction("Index", "Auth");
        } 
        [HttpPatch]
        public IActionResult Update([FromForm] UserDto dto, [FromServices] IUpdateUserCommand command)
        {
            if (this._service.Authenticated)
            {
                this._handler.HandleCommand(command, dto);
                return NoContent();
            }
            return RedirectToAction("Index", "Auth");
        }
    }
}

TestStore.Web/Views/Shared/Components/NavigationMenu/Default.cshtml
@using TestStore.Application.Dto
@model NavLinksUserDataDto
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestStore.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @foreach(var l in Model.NavLinks){
                            @if(l.Name == "Cart"){
                                <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index" id="accessCart">Cart</a>
                                </li>
                            }else{
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="@l.Controller" asp-action="@l.Action">@l.Name</a>
                                </li>
                            }
                        }
                        @if(string.IsNullOrEmpty(Model.Username)){
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Index">Sign in</a>
                        </li>
                        }else {
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            @Model.Username
                          </a>
                          <ul class="dropdown-menu">
                            <li><a class="dropdown-item"  asp-controller="Users" asp-action="Edit" asp-route-id="@Model.UserId">Edit profile</a></li>
                            @if(@Model.IsAdmin){
                                <li><a class="dropdown-item"  asp-controller="Adminpanel" asp-action="Index" >Admin panel</a></li>
                            }
                            <li><a class="dropdown-item" href="#" id="logout">Logout</a></li>
                          </ul>
                        </li>
                        }
                    </ul>
                </div>